apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: auth-ms
  name: auth-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-ms
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: auth-ms
    spec:
      containers:
        - image: cuevasgpablo/auth-ms
          name: auth-ms
          env:
            - name: PORT
              value: '3000'

            - name: NATS_SERVERS
              value: 'nats://nats:4222'

            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: auth.secret
                  key: JWT_SECRET

            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: auth.secret
                  key: DATABASE_URL
          resources: {}
status: {}
