apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: payments-ms
  name: payments-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments-ms
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: payments-ms
    spec:
      containers:
        - image: cuevasgpablo/payments-ms
          name: payments-ms
          env:
            - name: PORT
              value: '3000'

            - name: NATS_SERVERS
              value: 'nats://nats:4222'

            - name: STRIPE_SUCCESS_URL
              value: 'http://minikube:30417/api/v1/payments/success'

            - name: STRIPE_CANCEL_URL
              value: 'http://minikube:30417/api/v1/payments/cancelled'

            - name: STRIPE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: payments.secret
                  key: STRIPE_SECRET_KEY

            - name: STRIPE_ENDPOINT_SECRET
              valueFrom:
                secretKeyRef:
                  name: payments.secret
                  key: STRIPE_ENDPOINT_SECRET
          resources: {}
status: {}
